language: c
sudo: required
env:
#  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.0.0
#  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.0
   - OCAML_VERSION=4.01.0 OPAM_VERSION=1.2.0
#  - OCAML_VERSION=4.00.1 OPAM_VERSION=1.0.0
#  - OCAML_VERSION=4.00.1 OPAM_VERSION=1.1.0
#  - OCAML_VERSION=4.00.1 OPAM_VERSION=1.2.0
#  - OCAML_VERSION=3.12.1 OPAM_VERSION=1.0.0
#  - OCAML_VERSION=3.12.1 OPAM_VERSION=1.1.0
#  - OCAML_VERSION=3.12.1 OPAM_VERSION=1.2.0

addons:
  apt:
    packages:
      - ninja-build

before_script:
  - git clone --branch spirv-1.1-rev1 https://github.com/KhronosGroup/SPIRV-Tools.git ~/spirv-tools
  - git clone https://github.com/KhronosGroup/SPIRV-Headers.git ~/spirv-tools/external/spirv-headers

script: bash -ex .travis-ci.sh
